Adding the Start of Navigation
MandarinPine18/BITS-App pull request #11
Opened 2023-03-14 18:20 UTC by GalaxyManBlue

In this branch we finally introduced the **_Navigation_** feature into our program allowing us to switch between tabs on the main page and finally click into an article. The way we are using navigation within this branch is how we are planning to use it almost everywhere else (depending on what exactly we are wanting the user to see/do). 

Here is a checklist of items that occurred during this branch:
- Added a Category deserializer which allows a **Json to be converted to a C# object using Uri objects**
- Created a **tabbed view** with the start of some tabs we want to be  to be on the **HomePage** where the user starts in the app
- Deleted Files that we were able to modify and make better with the **use of CollectionViews and DataTemplates**
- **Updated from .NET Maui** 6.0 to 7.0

**And then just like any other programing update I've ever seen in my life:
- Fixed various bugs.
- Fixed performance issues.**

2023-03-14 18:42 UTC, MandarinPine18 requested changes
There's quite a few minor changes, and a lot of files which aren't being used at all. We really need to delete those. I would also go back and check for formatting, because there's a heck of a lot of that which needs to be fixed. See my comments. Besides the cleanup, it's looks great! Loving the design and the snappy functionality!

2023-03-14 18:42 UTC, MandarinPine18 commented on BITS-App/App.xaml.cs
> +        MainPage = new NavigationPage(new Pages.HomePage());
Ah yes, we set MainPage to a NavigationPage and then proceed to throw it away _immediately_

2023-03-14 18:42 UTC, MandarinPine18 commented on BITS-App/AppShell.xaml
I don't think we're even still using this file. We should just delete it.

2023-03-14 18:42 UTC, MandarinPine18 commented on BITS-App/AppShell.xaml.cs
Gotta delete this too

2023-03-14 18:42 UTC, MandarinPine18 commented on BITS-App/Models/PostsSet.cs
I don't think we're even using this prototype anymore either

2023-03-14 18:42 UTC, MandarinPine18 commented on BITS-App/Pages/AboutPage.xaml
This'll need some sprucing up, but that's for a later branch

2023-03-14 18:42 UTC, MandarinPine18 commented on BITS-App/Views/PostPage.xaml.cs
This should really be in the Pages folder

2023-03-15 02:32 UTC, MandarinPine18 approved these changes
Alrighty it looks good now

2023-03-15 02:35 UTC, merged

2023-03-15 02:35 UTC, GalaxyManBlue commented
-666... you removed the devil so that we chillin now good job :)